<?php

namespace Database\Seeders;

use App\Models\Genre;
use App\Models\Produit;
use App\Models\TypeProduit;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProduitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Retrieve genres and types from database
        $genres = Genre::pluck('id', 'nom')->toArray();
        $types = TypeProduit::pluck('id', 'nom')->toArray();

        $produits = [
            // HOMME
            [
                'nom' => 'Polo bleu marine homme',
                'description' => 'Polo élégant bleu marine en coton piqué, parfait pour un look raffiné et décontracté.',
                'prix' => 59.00,
                'image' => 'https://i.postimg.cc/FrsQ7Hpr/polo-bleumarine-homme.avif',
                'marque' => 'Sportify',
                'stock' => 70,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo bleu clair homme',
                'description' => 'Polo bleu clair léger et confortable, idéal pour les journées estivales.',
                'prix' => 52.00,
                'image' => 'https://i.postimg.cc/xC7ZZYB7/polo-bleu-clair-homme.avif',
                'marque' => 'UniWear',
                'stock' => 85,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo noir homme',
                'description' => 'Polo noir intemporel avec coupe ajustée, un classique de la garde-robe masculine.',
                'prix' => 64.00,
                'image' => 'https://i.postimg.cc/hjhwMh3c/polo-noir-homme.avif',
                'marque' => 'Sportify',
                'stock' => 65,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo orange foncé homme',
                'description' => 'Polo orange foncé vibrant, en tissu respirant pour un confort optimal.',
                'prix' => 55.00,
                'image' => 'https://i.postimg.cc/Y9VPPkTJ/polo-orangefonce-homme.avif',
                'marque' => 'ColorLine',
                'stock' => 50,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo blanc homme',
                'description' => 'Polo blanc classique, parfait pour un style propre et élégant en toute saison.',
                'prix' => 57.00,
                'image' => 'https://i.postimg.cc/Pxc77hBh/polo-polo-blanc-homme.avif',
                'marque' => 'UniWear',
                'stock' => 90,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo vert menthe homme',
                'description' => 'Polo vert menthe rafraîchissant, idéal pour les tenues estivales légères.',
                'prix' => 53.00,
                'image' => 'https://i.postimg.cc/MT4LLxhp/polo-vertmenthe-homme.avif',
                'marque' => 'ColorLine',
                'stock' => 75,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            // T-shirt Basique 
            [
                'nom' => 'T-shirt basique beige homme',
                'description' => 'T-shirt basique beige en coton doux, idéal pour un look neutre et moderne.',
                'prix' => 29.99,
                'image' => 'https://i.postimg.cc/C5mh3RHr/tshirt-basique-beige-homme.avif',
                'marque' => 'UniWear',
                'stock' => 110,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique blanc homme',
                'description' => 'T-shirt blanc classique 100% coton, un indispensable du dressing masculin.',
                'prix' => 25.99,
                'image' => 'https://i.postimg.cc/br3y7ZHM/tshirt-basique-blanc-homme.avif',
                'marque' => 'UniWear',
                'stock' => 120,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique bleu clair homme',
                'description' => 'T-shirt léger bleu clair, parfait pour un style estival décontracté.',
                'prix' => 32.50,
                'image' => 'https://i.postimg.cc/6qYWk8Lm/tshirt-basique-bleu-clair-homme.avif',
                'marque' => 'ColorLine',
                'stock' => 95,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique bleu marine homme',
                'description' => 'T-shirt basique bleu marine, coupe droite et tissu doux pour un confort durable.',
                'prix' => 37.00,
                'image' => 'https://i.postimg.cc/QC082Fkn/tshirt-basique-bleu-marine-homme.avif',
                'marque' => 'Sportify',
                'stock' => 90,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique gris chiné homme',
                'description' => 'T-shirt basique gris chiné, un essentiel polyvalent au quotidien.',
                'prix' => 28.00,
                'image' => 'https://i.postimg.cc/KjJG61DX/tshirt-basique-gris-chine-homme.avif',
                'marque' => 'UniWear',
                'stock' => 100,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique marron homme',
                'description' => 'T-shirt marron basique avec une teinte chaude et naturelle.',
                'prix' => 31.00,
                'image' => 'https://i.postimg.cc/4yBfDYQk/tshirt-basique-marron-homme.avif',
                'marque' => 'ColorLine',
                'stock' => 80,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique noir homme',                                                                                                                                              
                'description' => 'T-shirt noir basique, coupe moderne et tissu résistant pour un usage quotidien.',
                'prix' => 34.00,
                'image' => 'https://i.postimg.cc/wM0qC1cS/tshirt-basique-noir-homme.avif',
                'marque' => 'Sportify',
                'stock' => 120,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique rose homme',
                'description' => 'T-shirt rose pâle, une touche de couleur douce pour vos tenues décontractées.',
                'prix' => 35.90,
                'image' => 'https://i.postimg.cc/qqjJPNXP/tshirt-basique-rose-homme.avif',
                'marque' => 'ColorLine',
                'stock' => 70,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique vert clair homme',
                'description' => 'T-shirt vert clair basique, léger et agréable à porter pendant l’été.',
                'prix' => 33.90,
                'image' => 'https://i.postimg.cc/2y2ks17m/tshirt-basique-vert-claire-homme.avif',
                'marque' => 'UniWear',
                'stock' => 85,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique vert forêt homme',
                'description' => 'T-shirt vert forêt au ton profond, parfait pour un style naturel et sobre.',
                'prix' => 39.00,
                'image' => 'https://i.postimg.cc/7hmHF5nw/tshirt-basique-vert-foret-homme.avif',
                'marque' => 'Sportify',
                'stock' => 95,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            // T-shirt de luxe
            [
                'nom' => 'T-shirt de luxe beige homme',
                'description' => 'T-shirt de luxe beige en coton égyptien, douceur et élégance au rendez-vous.',
                'prix' => 78.00,
                'image' => 'https://i.postimg.cc/26xL5879/tshirt-de-luxe-beige-homme.webp',
                'marque' => 'EliteWear',
                'stock' => 40,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de luxe bleu homme',
                'description' => 'T-shirt bleu de luxe, confection haut de gamme et finitions irréprochables.',
                'prix' => 79.00,
                'image' => 'https://i.postimg.cc/wvkRBTQb/tshirt-de-luxe-bleu-homme.webp',
                'marque' => 'EliteWear',
                'stock' => 35,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de luxe bleu marine homme',
                'description' => 'T-shirt bleu marine luxueux, coupe ajustée et texture soyeuse.',
                'prix' => 75.00,
                'image' => 'https://i.postimg.cc/rm9RpFNn/tshirt-de-luxe-bleu-marine-homme.webp',
                'marque' => 'EliteWear',
                'stock' => 45,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de luxe gris homme',
                'description' => 'T-shirt gris haut de gamme, conçu pour allier confort et distinction.',
                'prix' => 74.00,
                'image' => 'https://i.postimg.cc/V6F0NLWV/tshirt-de-luxe-gris-homme.webp',
                'marque' => 'EliteWear',
                'stock' => 50,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de luxe noir homme',
                'description' => 'T-shirt noir premium en coton égyptien, design minimaliste et coupe parfaite.',
                'prix' => 77.00,
                'image' => 'https://i.postimg.cc/0jb5q8Wp/tshirt-de-luxe-noir-homme.webp',
                'marque' => 'EliteWear',
                'stock' => 30,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de luxe rose homme',
                'description' => 'T-shirt rose luxueux avec une finition satinée et un toucher exceptionnel.',
                'prix' => 76.00,
                'image' => 'https://i.postimg.cc/QtqKMxJz/tshirt-de-luxe-rose-homme.webp',
                'marque' => 'EliteWear',
                'stock' => 40,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de luxe vert clair homme',
                'description' => 'T-shirt vert clair raffiné, conçu avec des fibres naturelles ultra-douces.',
                'prix' => 72.00,
                'image' => 'https://i.postimg.cc/xCPNdT3B/tshirt-de-luxe-vert-claire-homme.webp',
                'marque' => 'EliteWear',
                'stock' => 35,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de luxe vert homme',
                'description' => 'T-shirt de luxe vert profond, parfait équilibre entre style et confort.',
                'prix' => 73.00,
                'image' => 'https://i.postimg.cc/V6F0NLWp/tshirt-de-luxe-vert-homme.webp',
                'marque' => 'EliteWear',
                'stock' => 40,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            // T-shirt de sport
            [
                'nom' => 'T-shirt de sport blanc homme',
                'description' => 'T-shirt de sport blanc respirant, idéal pour les entraînements intenses et le running.',
                'prix' => 49.90,
                'image' => 'https://i.postimg.cc/fbRRvjcg/tshirt-de-sport-blanc-homme.avif',
                'marque' => 'FitZone',
                'stock' => 100,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de sport bleu homme',
                'description' => 'T-shirt de sport bleu, conçu avec un tissu technique à séchage rapide.',
                'prix' => 54.90,
                'image' => 'https://i.postimg.cc/5t22mqBr/tshirt-de-sport-bleu-homme.avif',
                'marque' => 'FitZone',
                'stock' => 95,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de sport gris homme',
                'description' => 'T-shirt de sport gris, respirant et ultra-léger pour un confort maximal.',
                'prix' => 47.00,
                'image' => 'https://i.postimg.cc/nLhh1Y4P/tshirt-de-sport-gris-homme.avif',
                'marque' => 'FitZone',
                'stock' => 110,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de sport marron homme',
                'description' => 'T-shirt de sport marron avec technologie anti-transpiration pour garder la peau sèche.',
                'prix' => 52.00,
                'image' => 'https://i.postimg.cc/k5YXY6sy/tshirt-de-sport-marron-homme.avif',
                'marque' => 'FitZone',
                'stock' => 85,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de sport noir homme',
                'description' => 'T-shirt de sport noir avec design ergonomique, offre liberté de mouvement totale.',
                'prix' => 56.00,
                'image' => 'https://i.postimg.cc/432N27P0/tshirt-de-sport-noir-homme.avif',
                'marque' => 'FitZone',
                'stock' => 120,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de sport vert foncé homme',
                'description' => 'T-shirt de sport vert foncé, parfait pour les séances de musculation ou d’extérieur.',
                'prix' => 58.00,
                'image' => 'https://i.postimg.cc/FKCsCdp2/tshirt-de-sport-vert-fonce-homme.avif',
                'marque' => 'FitZone',
                'stock' => 90,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            // T-shirt imprimé
            [
                'nom' => 'T-shirt imprimé blanc homme',
                'description' => 'T-shirt imprimé blanc avec un motif minimaliste, idéal pour un look urbain décontracté.',
                'prix' => 38.00,
                'image' => 'https://i.postimg.cc/bNRPFSN9/tshirt-imprime-blanc-homme.avif',
                'marque' => 'ColorLine',
                'stock' => 100,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt imprimé bleu clair homme',
                'description' => 'T-shirt bleu clair avec imprimé graphique, parfait pour les tenues estivales.',
                'prix' => 36.90,
                'image' => 'https://i.postimg.cc/gkKpBLkD/tshirt-imprime-bleu-clair-homme.avif',
                'marque' => 'ColorLine',
                'stock' => 90,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt imprimé bleu marine homme',
                'description' => 'T-shirt imprimé bleu marine avec motif moderne et coupe confortable.',
                'prix' => 44.00,
                'image' => 'https://i.postimg.cc/wTkzbRTh/tshirt-imprime-bleu-marine-homme.avif',
                'marque' => 'ColorLine',
                'stock' => 80,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt imprimé noir homme',
                'description' => 'T-shirt noir imprimé avec motif streetwear, idéal pour un look branché.',
                'prix' => 46.00,
                'image' => 'https://i.postimg.cc/3JZhb0JV/tshirt-imprime-noir-homme.avif',
                'marque' => 'StreetMood',
                'stock' => 110,
                'genre_id' => $genres['Homme'] ?? 1,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            // Polo Femme
            [
                'nom' => 'Polo Blanc Bleu Foncé Femme',
                'description' => 'Polo élégant blanc avec détails bleu foncé, en coton piqué de haute qualité pour un confort optimal.',
                'prix' => 79.00,
                'image' => 'https://i.postimg.cc/YSKxG0Y5/tshirt-polo-blanc-bleu-fonce-femme.avif',
                'marque' => 'ClassicWear',
                'stock' => 65,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo Blanc Rayé Femme',
                'description' => 'Polo blanc avec fines rayures, alliant style sportif et élégance pour une tenue décontractée mais raffinée.',
                'prix' => 75.00,
                'image' => 'https://i.postimg.cc/LsKVY5jp/tshirt-polo-blanc-raye-femme.avif',
                'marque' => 'Sportify',
                'stock' => 55,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo Bleu Clair Femme',
                'description' => 'Polo bleu clair en coton respirant, parfait pour les journées ensoleillées et les occasions décontractées.',
                'prix' => 69.00,
                'image' => 'https://i.postimg.cc/43k17ypT/tshirt-polo-bleu-clair-femme.avif',
                'marque' => 'UniWear',
                'stock' => 70,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo Bleu Marine Femme',
                'description' => 'Polo bleu marine classique, intemporel et polyvalent, idéal pour compléter toute garde-robe féminine.',
                'prix' => 77.00,
                'image' => 'https://i.postimg.cc/wB8kyMDK/tshirt-polo-bleu-marine-femme.avif',
                'marque' => 'ClassicWear',
                'stock' => 60,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo Marron Femme',
                'description' => 'Polo marron élégant en coton doux, offrant confort et style pour un look automnal raffiné.',
                'prix' => 72.00,
                'image' => 'https://i.postimg.cc/pdfJDvBX/tshirt-polo-marron-femme.avif',
                'marque' => 'UniWear',
                'stock' => 45,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo Noir Femme',
                'description' => 'Polo noir sophistiqué, essentiel pour une tenue chic et facile à associer avec tous vos bas.',
                'prix' => 75.00,
                'image' => 'https://i.postimg.cc/MG7mywYq/tshirt-polo-noir-femme.avif',
                'marque' => 'ClassicWear',
                'stock' => 80,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo Rouge Femme',
                'description' => 'Polo rouge vif en coton de qualité, pour ajouter une touche de couleur audacieuse à votre style quotidien.',
                'prix' => 71.00,
                'image' => 'https://i.postimg.cc/PqWQmHM5/tshirt-polo-rouge-femme.avif',
                'marque' => 'Sportify',
                'stock' => 50,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],

            // T-shirt Basique Femme
            [
                'nom' => 'T-shirt Basique Blanc Femme',
                'description' => 'T-shirt basique blanc en coton 100%, essentiel intemporel pour toutes les tenues décontractées.',
                'prix' => 25.00,
                'image' => 'https://i.postimg.cc/MTrMB3gB/tshirt-basique-blanc-femme.avif',
                'marque' => 'Essential',
                'stock' => 120,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt Basique Blanc Rayé Femme',
                'description' => 'T-shirt blanc à rayures marinières, style casual et frais pour un look maritime élégant.',
                'prix' => 28.00,
                'image' => 'https://i.postimg.cc/rmY04Z7W/tshirt-basique-blanc-raye-femme.avif',
                'marque' => 'Nautical',
                'stock' => 85,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt Basique Bleu Marine Femme',
                'description' => 'T-shirt basique bleu marine en coton doux, parfait pour un style minimaliste et confortable.',
                'prix' => 27.00,
                'image' => 'https://i.postimg.cc/nzwjmSNv/tshirt-basique-bleu-marine-femme.avif',
                'marque' => 'Essential',
                'stock' => 95,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt Basique Marron Foncé Femme',
                'description' => 'T-shirt marron foncé en coton biologique, couleur terreuse pour un style naturel et tendance.',
                'prix' => 30.00,
                'image' => 'https://i.postimg.cc/MTrMB3gV/tshirt-basique-marron-fonce-femme.avif',
                'marque' => 'EcoWear',
                'stock' => 65,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt Basique Noir Femme',
                'description' => 'T-shirt basique noir universel, en coton stretch pour un confort et une durabilité exceptionnels.',
                'prix' => 26.00,
                'image' => 'https://i.postimg.cc/V6HrtZ24/tshirt-basique-noir-femme.avif',
                'marque' => 'Essential',
                'stock' => 110,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt Basique Rose Poudré Femme',
                'description' => 'T-shirt rose poudré délicat en coton doux, ajoutant une touche de douceur à votre garde-robe basique.',
                'prix' => 29.00,
                'image' => 'https://i.postimg.cc/fLgtdq18/tshirt-basique-rose-poudre-femme.avif',
                'marque' => 'Pastel',
                'stock' => 75,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],

            // T-shirt de Luxe Femme
            [
                'nom' => 'T-shirt de Luxe Bleu Clair Femme',
                'description' => 'T-shirt de luxe en soie et coton bleu clair, finition impeccable pour une élégance raffinée au quotidien.',
                'prix' => 65.00,
                'image' => 'https://i.postimg.cc/t4HkSD4t/tshirt-de-luxe-bleu-clair-femme.webp',
                'marque' => 'LuxeCotton',
                'stock' => 40,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de Luxe Gris Femme',
                'description' => 'T-shirt gris luxueux en jersey de qualité supérieure, coupe ajustée pour un style sophistiqué et contemporain.',
                'prix' => 68.00,
                'image' => 'https://i.postimg.cc/kgds1wgW/tshirt-de-luxe-gris-femme.webp',
                'marque' => 'PremiumWear',
                'stock' => 35,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de Luxe Jaune Femme',
                'description' => 'T-shirt jaune soleil en coton égyptien, couleur vibrante et tissu de qualité exceptionnelle.',
                'prix' => 63.00,
                'image' => 'https://i.postimg.cc/SxpdTVxf/tshirt-de-luxe-jaune-femme.webp',
                'marque' => 'LuxeCotton',
                'stock' => 30,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de Luxe Noir Femme',
                'description' => 'T-shirt noir premium en coton peigné, finition parfaite pour une élégance intemporelle et polyvalente.',
                'prix' => 70.00,
                'image' => 'https://i.postimg.cc/nht2RThK/tshirt-de-luxe-noir-femme.webp',
                'marque' => 'PremiumWear',
                'stock' => 45,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de Luxe Orange Femme',
                'description' => 'T-shirt orange luxueux en tissu respirant, couleur audacieuse pour un style affirmé et raffiné.',
                'prix' => 62.00,
                'image' => 'https://i.postimg.cc/2SfGcTST/tshirt-de-luxe-orange-femme.webp',
                'marque' => 'LuxeCotton',
                'stock' => 28,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de Luxe Rose Femme',
                'description' => 'T-shirt rose élégant en coton biologique de qualité supérieure, douceur et confort inégalés.',
                'prix' => 67.00,
                'image' => 'https://i.postimg.cc/t4HkSD4B/tshirt-de-luxe-rose-femme.webp',
                'marque' => 'PremiumWear',
                'stock' => 38,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de Luxe Vert Femme',
                'description' => 'T-shirt vert luxueux en mélange de lin et coton, couleur naturelle pour un style chic et décontracté.',
                'prix' => 64.00,
                'image' => 'https://i.postimg.cc/Qdrm4Sd0/tshirt-de-luxe-vert-femme.webp',
                'marque' => 'LuxeCotton',
                'stock' => 32,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],

            // T-shirt de Sport Femme - CORRIGÉ
            [
                'nom' => 'T-shirt de Sport Blanc Femme',
                'description' => 'T-shirt de sport blanc technique en tissu respirant, idéal pour les entraînements intensifs.',
                'prix' => 45.00,
                'image' => 'https://i.postimg.cc/DfX19sDW/tshirt-sport-blanc-femme.webp',
                'marque' => 'ActiveFit',
                'stock' => 90,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de Sport Bleu Clair Femme',
                'description' => 'T-shirt de sport bleu clair avec technologie d\'évacuation de l\'humidité, pour un confort optimal pendant l\'exercice.',
                'prix' => 48.00,
                'image' => 'https://i.postimg.cc/FFL0McqJ/tshirt-sport-bleu-clair-femme.webp',
                'marque' => 'SportTech',
                'stock' => 75,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de Sport Marron Femme',
                'description' => 'T-shirt de sport marron en tissu stretch, parfait pour le yoga et les activités de fitness en salle.',
                'prix' => 47.00,
                'image' => 'https://i.postimg.cc/XNC9RFhB/tshirt-sport-marron-femme.webp',
                'marque' => 'ActiveFit',
                'stock' => 60,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de Sport Noir Femme',
                'description' => 'T-shirt de sport noir performant avec ventilation stratégique, conçu pour les sportives exigeantes.',
                'prix' => 50.00,
                'image' => 'https://i.postimg.cc/L41jcf7Y/tshirt-sport-noir-femme.webp',
                'marque' => 'SportTech',
                'stock' => 85,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de Sport Rose Femme',
                'description' => 'T-shirt de sport rose en tissu léger et respirant, coupe féminine pour un style sportif élégant.',
                'prix' => 46.00,
                'image' => 'https://i.postimg.cc/VsCXxMTt/tshirt-sport-rose-femme.webp',
                'marque' => 'ActiveFit',
                'stock' => 70,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de Sport Vert Armée Femme',
                'description' => 'T-shirt de sport vert armée technique, coupe performante pour les activités outdoor et la course à pied.',
                'prix' => 52.00,
                'image' => 'https://i.postimg.cc/Pfw1gZcZ/tshirt-sport-vert-armee-femme.webp',
                'marque' => 'SportTech',
                'stock' => 55,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],

            // T-shirt Imprimé Femme
            [
                'nom' => 'T-shirt Imprimé Blanc Paris Femme',
                'description' => 'T-shirt blanc avec impression Paris romantique, pour afficher votre amour de la ville lumière avec style.',
                'prix' => 35.00,
                'image' => 'https://i.postimg.cc/HLrrQ118/tshirt-imprime-blanc-paris-femme.avif',
                'marque' => 'UrbanPrint',
                'stock' => 65,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt Imprimé Blanc Poésie Femme',
                'description' => 'T-shirt blanc avec impression poétique délicate, pour les amoureuses de littérature et d\'art.',
                'prix' => 38.00,
                'image' => 'https://i.postimg.cc/d0hh8ccm/tshirt-imprime-blanc-poesie-femme.avif',
                'marque' => 'ArtWear',
                'stock' => 50,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt Imprimé Gris Foncé Femme',
                'description' => 'T-shirt gris foncé avec impression graphique moderne, pour un style urbain et contemporain.',
                'prix' => 37.00,
                'image' => 'https://i.postimg.cc/jjDDzYYJ/tshirt-imprime-gris-fonce-femme.avif',
                'marque' => 'UrbanPrint',
                'stock' => 58,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt Imprimé Marron Foncé Femme',
                'description' => 'T-shirt marron foncé avec impression ethnique, inspiration bohème pour un style unique et voyageur.',
                'prix' => 40.00,
                'image' => 'https://i.postimg.cc/9fDDGHHp/tshirt-imprime-marron-fonce-femme.avif',
                'marque' => 'BohoStyle',
                'stock' => 45,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt Imprimé Noir Paris Femme',
                'description' => 'T-shirt noir avec impression Paris stylisée, design audacieux pour un look urbain et sophistiqué.',
                'prix' => 39.00,
                'image' => 'https://i.postimg.cc/g0xxvbbN/tshirt-imprime-noir-paris-femme.avif',
                'marque' => 'UrbanPrint',
                'stock' => 52,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt Imprimé Orange Femme',
                'description' => 'T-shirt orange vif avec impression géométrique, pour un style énergique et plein de vitalité.',
                'prix' => 36.00,
                'image' => 'https://i.postimg.cc/8C77hggK/tshirt-imprime-orange-femme.avif',
                'marque' => 'ArtWear',
                'stock' => 48,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt Imprimé Rose Pêche Femme',
                'description' => 'T-shirt rose pêche avec impression florale délicate, romantique et féminin pour un style printanier.',
                'prix' => 34.00,
                'image' => 'https://i.postimg.cc/zfyynYYQ/tshirt-imprime-rose-peche-femme.avif',
                'marque' => 'BohoStyle',
                'stock' => 55,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt Imprimé Rouge Femme',
                'description' => 'T-shirt rouge avec impression artistique abstraite, pour celles qui osent les couleurs et les designs audacieux.',
                'prix' => 41.00,
                'image' => 'https://i.postimg.cc/R0WWcxx8/tshirt-imprime-rouge-femme.avif',
                'marque' => 'ArtWear',
                'stock' => 42,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt Imprimé Vert Femme',
                'description' => 'T-shirt vert avec impression nature et feuillages, pour un style écologique et connecté à la nature.',
                'prix' => 37.00,
                'image' => 'https://i.postimg.cc/pd3pCcPZ/tshirt-imprime-vert-femme.avif',
                'marque' => 'BohoStyle',
                'stock' => 47,
                'genre_id' => $genres['Femme'] ?? 2,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            // 🟩 POLOS ENFANT
            [
                'nom' => 'Polo blanc enfant',
                'description' => 'Polo blanc classique en coton doux, parfait pour les journées d\'école et les sorties décontractées.',
                'prix' => 45.00,
                'image' => 'https://i.postimg.cc/yNybXthc/tshirt-polo-blanc-enfant.avif',
                'marque' => 'MiniStyle',
                'stock' => 60,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo bleu clair enfant',
                'description' => 'Polo bleu clair léger et respirant, idéal pour l\'été et les activités en plein air.',
                'prix' => 48.00,
                'image' => 'https://i.postimg.cc/xCjFs5gN/tshirt-polo-bleu-clair-enfant.avif',
                'marque' => 'YoungWear',
                'stock' => 50,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo bleu marine enfant',
                'description' => 'Polo bleu marine élégant en coton piqué, alliant confort et style pour les jeunes.',
                'prix' => 52.00,
                'image' => 'https://i.postimg.cc/rmyYhjgW/tshirt-polo-bleu-marine-enfant.avif',
                'marque' => 'MiniStyle',
                'stock' => 70,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo rouge enfant',
                'description' => 'Polo rouge vif pour enfant, une touche de couleur pour un look plein d\'énergie.',
                'prix' => 45.00,
                'image' => 'https://i.postimg.cc/3RrbL19G/tshirt-polo-rouge-enfant.avif',
                'marque' => 'ColorKid',
                'stock' => 55,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],
            [
                'nom' => 'Polo vert enfant',
                'description' => 'Polo vert tendance, conçu pour offrir confort et liberté de mouvement.',
                'prix' => 42.00,
                'image' => 'https://i.postimg.cc/G23SMKzX/tshirt-polo-vert-enfant.avif',
                'marque' => 'EcoLine',
                'stock' => 65,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['Polo'] ?? 3,
            ],

            // 🟦 T-SHIRT BASIQUE ENFANT
            [
                'nom' => 'T-shirt basique beige enfant',
                'description' => 'T-shirt basique beige doux et confortable, idéal pour un usage quotidien.',
                'prix' => 25.00,
                'image' => 'https://i.postimg.cc/668Nt6L8/tshirt-basique-beige-enfant.avif',
                'marque' => 'MiniStyle',
                'stock' => 80,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique blanc enfant',
                'description' => 'T-shirt blanc basique en coton biologique, parfait pour toutes les tenues.',
                'prix' => 22.00,
                'image' => 'https://i.postimg.cc/h4Xqc4b7/tshirt-basique-blanc-enfant.avif',
                'marque' => 'EcoLine',
                'stock' => 100,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique bleu enfant',
                'description' => 'T-shirt bleu basique à la coupe droite, pour un confort absolu.',
                'prix' => 28.00,
                'image' => 'https://i.postimg.cc/fWVhDWj9/tshirt-basique-bleu-enfant.avif',
                'marque' => 'YoungWear',
                'stock' => 70,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],
            [
                'nom' => 'T-shirt basique vert enfant',
                'description' => 'T-shirt vert basique au design simple et agréable à porter tous les jours.',
                'prix' => 26.00,
                'image' => 'https://i.postimg.cc/CMRVSMHk/tshirt-basique-vert-enfant.avif',
                'marque' => 'MiniStyle',
                'stock' => 75,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt basique'] ?? 1,
            ],

            // 🟥 T-SHIRT DE LUXE ENFANT - CORRIGÉ
            [
                'nom' => 'T-shirt de luxe blanc enfant',
                'description' => 'T-shirt blanc de luxe en coton premium, doux et raffiné pour un style chic.',
                'prix' => 65.00,
                'image' => 'https://i.postimg.cc/4dMqmtbM/tshirt-de-luxe-blanc-enfant.webp',
                'marque' => 'Petit Luxe',
                'stock' => 40,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],
            [
                'nom' => 'T-shirt de luxe noir enfant',
                'description' => 'T-shirt noir de luxe au toucher soyeux et coupe élégante, parfait pour les occasions spéciales.',
                'prix' => 68.00,
                'image' => 'https://i.postimg.cc/vBjkc9Lk/tshirt-de-luxe-noir-enfant.webp',
                'marque' => 'Petit Luxe',
                'stock' => 35,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt de luxe'] ?? 5,
            ],

            // 🟨 T-SHIRT DE SPORT ENFANT
            [
                'nom' => 'T-shirt de sport blanc enfant',
                'description' => 'T-shirt de sport blanc respirant, parfait pour les entraînements et les jeux extérieurs.',
                'prix' => 35.00,
                'image' => 'https://i.postimg.cc/cJk5bYjx/tshirt-de-sport-blanc-enfant.avif',
                'marque' => 'ActiveKid',
                'stock' => 90,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de sport noir enfant',
                'description' => 'T-shirt de sport noir anti-transpiration, offrant confort et performance.',
                'prix' => 38.00,
                'image' => 'https://i.postimg.cc/QMYny5Pd/tshirt-de-sport-noir-enfant.avif',
                'marque' => 'ActiveKid',
                'stock' => 85,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],
            [
                'nom' => 'T-shirt de sport rose enfant',
                'description' => 'T-shirt rose vif pour enfant, conçu pour le sport et les activités dynamiques.',
                'prix' => 33.00,
                'image' => 'https://i.postimg.cc/LsQ0bf74/tshirt-de-sport-rose-enfant.avif',
                'marque' => 'ActiveKid',
                'stock' => 75,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt de sport'] ?? 4,
            ],

            // 🟪 T-SHIRT IMPRIMÉ ENFANT
            [
                'nom' => 'T-shirt imprimé beige enfant',
                'description' => 'T-shirt beige imprimé avec motif amusant, idéal pour un look décontracté.',
                'prix' => 29.00,
                'image' => 'https://i.postimg.cc/nLW0kxjm/tshirt-de-imprime-beige-enfant.avif',
                'marque' => 'FunStyle',
                'stock' => 80,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt imprimé blanc enfant',
                'description' => 'T-shirt blanc imprimé avec design coloré, pour un style original et joyeux.',
                'prix' => 32.00,
                'image' => 'https://i.postimg.cc/rpHQJT00/tshirt-de-imprime-blanc-enfant.avif',
                'marque' => 'ColorKid',
                'stock' => 70,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt imprimé bleu clair enfant',
                'description' => 'T-shirt bleu clair imprimé à motif graphique, doux et tendance.',
                'prix' => 31.00,
                'image' => 'https://i.postimg.cc/MGLdDwMj/tshirt-de-imprime-bleu-clair-enfant.avif',
                'marque' => 'FunStyle',
                'stock' => 65,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt imprimé bleu enfant',
                'description' => 'T-shirt bleu imprimé avec motif amusant, parfait pour tous les jours.',
                'prix' => 29.00,
                'image' => 'https://i.postimg.cc/GpfqQR8y/tshirt-de-imprime-bleu-enfant.avif',
                'marque' => 'MiniStyle',
                'stock' => 85,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt imprimé gris foncé enfant',
                'description' => 'T-shirt gris foncé imprimé à motif moderne, idéal pour un look urbain.',
                'prix' => 34.00,
                'image' => 'https://i.postimg.cc/k4twYHK4/tshirt-de-imprime-gris-fonce-enfant.avif',
                'marque' => 'YoungWear',
                'stock' => 60,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt imprimé noir enfant',
                'description' => 'T-shirt noir imprimé avec design audacieux, pour un style affirmé.',
                'prix' => 36.00,
                'image' => 'https://i.postimg.cc/85rwXYMC/tshirt-de-imprime-noir-enfant.avif',
                'marque' => 'ColorKid',
                'stock' => 55,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
            [
                'nom' => 'T-shirt imprimé vert enfant',
                'description' => 'T-shirt vert imprimé au motif naturel, léger et agréable à porter.',
                'prix' => 30.00,
                'image' => 'https://i.postimg.cc/9Mq1gkZD/tshirt-de-imprime-vert-enfant.avif',
                'marque' => 'FunStyle',
                'stock' => 68,
                'genre_id' => $genres['Enfant'] ?? 3,
                'type_produit_id' => $types['T-shirt imprimé'] ?? 2,
            ],
        ];


        foreach ($produits as $produit) {
            Produit::create($produit);
        }
    }
}
